### ISSUE TITLE
Artemis

### ISSUE THREAD

**Issue by zidane9000123** [sodimm/RebornBuddy#10]
Is there an ETA on when Artemis might be back up ?

**Comment by sodimm** [comment]
Artemis isn't down... whats the issue you're having?

**Comment by zidane9000123** [comment]
[04:44:35.198 N] [Artemis Debugging] Start Point :: Chocobo Square
[04:44:35.216 N] Adding Chanko Hook
[04:44:36.574 N] [Chanko] Eating Antelope Steak
[04:44:36.621 D] DoAction Item 4643 0xE0000000
[04:44:45.688 D] DoAction Spell 3 0x106A4A3C

i just says debugging and i can just interact with my character like usual ? i have tried teleporting to different areas where the hunts are located and it still doesn't move to the enemy location

**Comment by sodimm** [comment]
delete the Artemis folder, make a new one and download the updated Loader. Dont SVN Checkout the Loader or the download will fail. Once its downloaded the new version. Open the BotBase Settings and ensure "Do Hunt Bills" is selected, then press Start. You should join the discord. See the Faq on RB discord.

**Comment by zidane9000123** [comment]
thanks for the fast response it worked your a magician :D
