### ISSUE TITLE
Sodimm profile vath issues

### ISSUE THREAD

**Issue by zidane9000123** [sodimm/RebornBuddy#11]
So i noticed a few issues pop up when i execute the vath daily quest. There are instances for example when you are trying to speak with Vath kintamer that the plugin never continues because the flight plugin gets stuck above the NPC.
Another bug that pops up is when you start quests from Vath Kintamer like Shoo fly, dont bother me it successfully finishes one location then unmounts after one iteration uses your regular mount and moves to second objective unable to fulfill due to not having right mount. 
Also do you have any tips for sea of clouds the navigation seems to have some issues in that area is their a global setting that is preferred in each area if so could you assist me. 
Again Thank you for taking the time to read this.

**Comment by sodimm** [comment]
the dismount issue is fixed, the flight issues are exbuddy. wont be an issue once flightor releases.
