### ISSUE TITLE
Artemis pathing issue - The Churning Mists

### ISSUE THREAD

**Issue by NicoleKCat** [sodimm/RebornBuddy#13]
Artemis teleports to Zenith when the user has any marks in The Churning Mists. 

When paired with a flying plugin, this causes the user to get stuck trying to path around the extremely large towering structures in the area around the Zenith aetheryte, eventually crashing the application. 

Suggested solution; teleport to Moghome instead. 

Pathing to hunts on the western side of the map will take slightly longer, but there isn't anything to get stuck on. 

Issue occurs towards end of the following rb log: 
[19972 2017-09-27 04.37.txt](https://github.com/sodimm/RebornBuddy/files/1337146/19972.2017-09-27.04.37.txt)

**Comment by sodimm** [comment]
Without creating an elaborate system to plot out it's exact movements, there's no way around this ExBuddy issue. Artemis originally used Mog Home, but caused more, not less issues than Zenith. The release of Flightor will eradicate these Issues. Soon ;).
