### ISSUE TITLE
Profiles are not working 90% of the time.

### ISSUE THREAD

**Issue by Azerdeth** [sodimm/RebornBuddy#17]
Very unreliable profiles, keep throwing errors around. "Element SoTurnIn" is not supported, "element SoTalkTo" is not supported.

It's a dice roll if anything works or not. One day it works, the other its completely fucked.

**Comment by sodimm** [comment]
Your folder structure must be EXACTLY as it is on GitHub. If you're downloading a single profile and loading it; it wont work. Most of the profiles require custom behaviors (SoTalkTo etc) to function, if these behaviors aren't there they're not going to work. Please ensure you've installed them correctly.
