### ISSUE TITLE
Profiles not using mounts.

### ISSUE THREAD

**Issue by guppysb** [sodimm/RebornBuddy#26]
Hello Sodimm,

Thank you very much for creating the profiles. It's very evident that a lot of work went into them. 

I have noticed that my profiles don't use mounts, especially the \Sodimm\trunk\Profiles\Sodimm\Crafting\[OrderBot] [Lisbeth 3.0] Crafting Class Quests.xml. Any way I can fix this? 

Thank you again!

**Comment by Antony256** [comment]
If you stop the profile while lisbeth is running your mount setting in "Global Settings" will be disabled.

**Comment by guppysb** [comment]
good to know, thank you.
