### ISSUE TITLE
Sylph Rank 1: Will not go back to get Goobbue mount.

### ISSUE THREAD

**Issue by mattarolla** [sodimm/RebornBuddy#3]
Quest: Giddy for Goobbues

If the bot somehow gets knocked off the Goobbue mount (gets aggro and then gets off to kill monster), it does not go back to reacquire the Goobbue and will just stand on a normal mount on front of the thing it was trying to kill.

Note: I was afk so I didn't get to see if it picked up the mount in the first place.

**Comment by sodimm** [comment]
it shouldn't be dismounting for combat, it should ignore it. i'll look into this.

**Comment by mattarolla** [comment]
So I was actually not afk this time, and I saw it dismount the Goobbue to kill a Dream toad that it drew attention from.

**Comment by mattarolla** [comment]
[22:27:13.635 D] [POI Set] Type: Kill, Name: Dreamtoad, ObjectId: 4004B62E, NpcId: 164, Location: <357.3204, -18.10974, -144.6708>

that is what made it get off

note: i didn't have any quest involving Dreamtoad

Would it help to attach the complete log?
