### ISSUE TITLE
Ixal Rank 5 - Craft/Handin Code Chunk Missing HW Jobs

### ISSUE THREAD

**Issue by mattarolla** [sodimm/RebornBuddy#6]
I noticed during Ixal Rank 5 my game client would freeze when RB tried to change into a crafter.

The code chunk for gear change for craft and hand in class is missing the HW jobs, but I just removed the problematic code and it fixed it.

**Comment by sodimm** [comment]
yeah these were made pre-heavensward, i do have rough drafts of the combined profile, but i've no way of testing it until i'm resubbed.

**Comment by sodimm** [comment]
fixed in restructure
