### ISSUE TITLE
3.0 Beast Tribe Dailies -

### ISSUE THREAD

**Issue by sleepyeyed** [sodimm/RebornBuddy#7]
Quests with Vundu sundance emote:  Character will target the NPC but the emote does not execute. Quest names are "Dance Commander, Electric Gunduloo, and Wildwort and Sundrop"

Vath Quest "Fifty Shades of Yellow" where you must type something is /say:  The profile does the say action too quickly after targeting the NPC and the NPC does not register it.

**Comment by sodimm** [comment]
it should try again after 10secs... if it doesn't it's broken... and i'll have to take a looksee. The whole lot needs a rework.

**Comment by sodimm** [comment]
fixed in the restructure.
